default: &default
  adapter: postgresql
  database: <%= "rails_tutorial_#{ENV['RAILS_ENV']}" %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  pool: <%= ENV['POSTGRES_POOL_SIZE'] %>
  timeout: <%= ENV['POSTGRES_TIMEOUT'] %>
  template: template0

development:
  << : *default

test:
  << : *default

production:
  << : *default
